apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u91amnr63-python
  janus-idp.io/tekton: u91amnr63-python
  backstage.io/kubernetes-id: u91amnr63-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u91amnr63-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
